export { default as ImgComp } from "./ImgComp";
export { default as Logo } from "./Logo";
export { default as PostImg } from "./PostImg";
export { default as PostVideo } from "./PostVideo";
export { default as TextareaComp } from "./TextareaComp";
export { default as VidComp } from "./VidComp";
export { default as Search } from "./Search";
export { default as Trending } from "./Trending";
export { default as Recommendations } from "./Recommendations";
